import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link';

export default function MovieDetails({info}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Movie Catalog | All informations about all movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {info.title}
        </h1>
        <h2>
          {info.overview}
        </h2>

        <p>Score: {info.vote_average}</p>

        <div className={styles.grid}>

          <Link href="/search">
            Search for a specific movie
          </Link>
          
            <img src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} width={150} height={150}></img>
            
               
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context){ 

  const res = await fetch(`http://localhost:3000/api/movie/${context.params.id}`)
  const json = await res.json();

  console.log("JSON", json)

  return{
    props: {
      info: json.info
    }
  };
}