import Head from 'next/head'
import Image from 'next/image'
import Styles from '../styles/Home.module.css'
import Logo from '../public/assets/netflix-logo.png'

export default function Home({ list }) {
  return (
    <div className={Styles.container}>
      <div className={Styles.overlay}></div>
      <Head>
        <title>Netflix - Watch series online, wacth movies online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="#" />
      </Head>

      <div>
        <header className={Styles.header}>
          <Image className={Styles.logo} src={Logo} alt="Netflix Logo" width="167" height="45" />
          <div className={Styles.language}><select>
            <option value="Portuguese">Portuguese</option>
            <option value="English">English</option>
          </select>
            <button className={Styles.button}>Sign In</button>
          </div>
        </header>
        
        <div className={Styles.heading}>
          <h1>Unlimited movies, TV shows, and more.</h1>
          <h2>Watch anywhere. Cancel anytime.</h2>
          <h3>Ready to watch? Enter your email to create or restart your membership.</h3>
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps() {

  const res = await fetch('http://localhost:3000/api/trend')
  const json = await res.json();

  return {
    props: {
      list: json.list
    }
  };
}