import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import { useState } from 'react'

export default function Search({list}) {

  const [searchText, setSearchText ] = useState('');
  const [ movieList, setMovieList ] = useState([]);

  const handleSearch = async () =>{
    if(searchText !== ''){
      const result = await fetch(`http://localhost:3000/api/search?q=${searchText}`);
      const json = await result.json();
      setMovieList(json.list)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Movie Catalog | All informations about all movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <input type="text" onChange={e=>setSearchText(e.target.value)}/>
        <span>Resultados para o termo: {searchText}</span>
        <button onClick={handleSearch}>Search</button>

        <hr/>

        <ul>
          {movieList.map(item=>(
            <li>
            <a href={`/movie/${item.id}`}>
                <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width='400px'></img>
                {item.title}
            </a>
          </li>
          ))}
        </ul>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}